name: CI - Code Quality / Release

on:
  push:
    branches:
      - master

  pull_request:

  workflow_dispatch:
    inputs:
      skip_checks:
        description: 'Skip code quality checks'
        required: false
        default: true
        type: boolean

jobs:
  release:
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message , '[skip ci]') &&
      !(github.event_name == 'pull_request' && startsWith(github.head_ref, 'renovate/'))
    environment: production
    env:
      NX_BASE: origin/${{ github.event_name == 'pull_request' && github.base_ref || 'master' }}
      TARGET_BRANCH: origin/${{ github.event_name == 'pull_request' && github.base_ref || 'master' }}
      # NX_CLOUD_ACCESS_TOKEN: ${{ vars.NX_CLOUD_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.FULL_TOKEN }}

      - name: Enable Corepack
        run: corepack enable

      - name: Set latest Yarn
        run: yarn set version stable

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
          cache-dependency-path: './yarn.lock'
          always-auth: true

      - name: Install dependencies
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn install --immutable

      - name: Check code quality
        if: ${{ !inputs.skip_checks }}
        run: yarn cq

      - uses: ExpediaGroup/package-json-validator@v1.6.0
        if: ${{ !inputs.skip_checks }}
        with:
          rules: |
            ranges
            tags
          dependency-types: |
            dependencies
            devDependencies
          ignore-packages: |
            @jscutlery/semv
          allowed-ranges: ^

      - uses: actions/setup-node@v4
        if: github.ref_name == 'master' || false
        with:
          cache: 'yarn'
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'

      - name: Release
        if: github.ref_name == 'master' || false
        env:
          NODE_AUTH_TOKEN: ${{ secrets.FULL_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          yarn release

      - name: Print install strings
        if: github.ref_name == 'master' || false
        run: ./tools/install-strings-list.sh
      # - uses: nrwl/nx-set-shas@v4
      #   with:
      #     main-branch-name: master

      # - run: git branch --track master origin/master
      #   if: ${{ github.event_name == 'pull_request' }}

      # - run: yarn nx-cloud record -- nx format:check
      # - run: yarn nx affected -t lint build
